version: '3.6'
networks:
  internal-net:
   name: workbench_subnet
services:
  backend:
    image: openjdk:11.0.1
    container_name: backend
    networks:
      - internal-net
    volumes:
      - ./backend/build/libs:/opt/assets/
    ports:
      - 8080:8080
    command: java -jar /opt/assets/chappuis-halder-1.0.jar
  # db:
    # image: postgres:10.5
    # container_name: db
    # restart: always
    # volumes:
      # - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    # environment:
      # POSTGRES_PASSWORD: example
    # ports:
    # networks:
      # - "5432:5432"
      # - internal-net
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - 4200:80
    depends_on:
      - backend
    volumes:
      - ./frontend/dist/:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal-net